# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
  - stage: A
    jobs:
      - job: primero
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                pwd
                mkdir C:\prueba
                $Url = "https://releases.hashicorp.com/terraform/1.3.8/terraform_1.3.8_windows_386.zip"
                $DownloadZipFile = "C:\prueba\" + $(Split-Path -Path $Url -Leaf)
                $ExtractPath = "C:\prueba\"
                Invoke-WebRequest -Uri $Url -OutFile $DownloadZipFile
                $ExtractShell = New-Object -ComObject Shell.Application 
                $ExtractFiles = $ExtractShell.Namespace($DownloadZipFile).Items()
                $ExtractShell.NameSpace($ExtractPath).CopyHere($ExtractFiles) 
                Start-Process $ExtractPath
            
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: MyBuildOutputs  
                      
