# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Proyecto API

stages:
  - stage: A
    jobs:
      - job: primero
        steps:     
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              secureVarsFile: '.env'
              commandOptions: 'https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_arm64.zip'
              allowTelemetryCollection: true

          - task: PublishBuildArtifacts@1
            displayName: Publish
            inputs: 
              pathToPublish: $(Build.SourcesDirectory)
              artifactName: MyBuildOutputs  
            