# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Proyecto API

stages:
  - stage: A
    jobs:
      - job: primero
        steps:     
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              allowTelemetryCollection: true
          - task: TerraformCLI@0
            inputs:
              command: 'plan'
              secureVarsFile: '.env'
              commandOptions: '-out main.tfplan'
              allowTelemetryCollection: true
          - task: TerraformCLI@0
            inputs:
              command: 'apply'
              secureVarsFile: '.env'
              allowTelemetryCollection: true

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)\genesysclou\terraform.tfstated'
              Contents: '**'
              TargetFolder: '$(Build.Artifac\tStagingDirectory)\genesysclou\tfstate'
          - task: PublishBuildArtifacts@1
            displayName: Publish
            inputs: 
              pathToPublish: $(Build.SourcesDirectory)
              artifactName: MyBuildOutputs  
            