# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
  - stage: A
    jobs:
      - job: primero
        steps:
          - task: PowerShell@2
            displayName: Install Terraform
            inputs:
              targetType: 'inline'
              script: |
                $Env:GENESYSCLOUD_CURRENT_LOCATION = Get-Location
                $Env:GENESYSCLOUD_CURRENT_LOCATION += '\prueba'
                mkdir $Env:GENESYSCLOUD_CURRENT_LOCATION
                $Url = "https://releases.hashicorp.com/terraform/1.3.8/terraform_1.3.8_windows_386.zip"
                $DownloadZipFile = $Env:GENESYSCLOUD_CURRENT_LOCATION + $(Split-Path -Path $Url -Leaf)
                $ExtractPath = $Env:GENESYSCLOUD_CURRENT_LOCATION
                echo $GENESYSCLOUD_CURRENT_LOCATION
                echo $ExtractPath
                echo $DownloadZipFile
                Invoke-WebRequest -Uri $Url -OutFile $DownloadZipFile
                cd $Env:GENESYSCLOUD_CURRENT_LOCATION
                
                $ExtractShell = New-Object -ComObject Shell.Application 
                $ExtractFiles = $ExtractShell.Namespace($DownloadZipFile).Items()
                $ExtractShell.NameSpace($ExtractPath).CopyHere($ExtractFiles) 
                Start-Process $ExtractPath
                
          - script: echo $(Build.ArtifactStagingDirectory)
                    echo $(buildConfiguration)
                    echo $(Agent.BuildDirectory)
                    echo $(System.DefaultWorkingDirectory)
                    echo $(Build.SourcesDirectory)
          - task: PowerShell@2
            displayName: Pruebas powershell
            inputs:
              targetType: 'inline'
              script: |
                dir


          - task: PublishBuildArtifacts@1
            displayName: Publish
            inputs: 
              pathToPublish: $(Build.SourcesDirectory)
              artifactName: MyBuildOutputs  
            
                      